// Automated job-radar runs update this file. Keep each id stable so saved user progress survives data refreshes.
window.ROLEBOARD_DATA = {
  updated: "03 Sep 2026",
  jobs: [
    {id:"weekday-swe-intern",company:"Weekday Works",role:"Software Engineer Intern",type:"Internship",location:"Bengaluru / Remote",mode:"Remote",pay:"₹30,000–₹50,000/month",postedOn:"2026-09-03",posted:"Posted 03 Sep 2026",deadline:"Applications open",urgent:true,eligibility:"2026 and 2027 graduates",confidence:"Medium-High · live Apply Now button",about:"Work alongside experienced engineers on real software projects, assisting with feature design, development, testing, debugging and performance improvements. The broad requirements accept Python, JavaScript, Java or C++ plus DSA, GitHub, cloud and AI/ML exposure.",apply:"https://hiredoor.in/jobs/software-engineer-intern-e43f12",source:"https://hiredoor.in/jobs/software-engineer-intern-e43f12"},
    {id:"pearson-payroll-frontend-intern",company:"Pearson",role:"Software Engineering Intern — Global Payroll Technology",type:"Internship",location:"Bengaluru",mode:"Hybrid",pay:"₹30,000/month",postedOn:"2026-09-03",posted:"Posted 03 Sep 2026",deadline:"Applications open",urgent:true,eligibility:"2026 and 2027 graduates",confidence:"High · live employer application",about:"Build React and TypeScript interfaces for Pearson's Global Command Center, an enterprise payroll operations and analytics platform. Responsibilities include reusable responsive components, dashboards, REST API integration, debugging, testing and performance optimisation.",apply:"https://pearson.jobs/bangalore-ind/associate-software-engineer-intern/60B518B3E9E74BF6BA34DD5D28B23DEE/job/",source:"https://hiredoor.in/jobs/software-engineering-intern-global-payroll-technology-team-2d610d"},
    {id:"nxtpe-java-backend-intern",company:"NxtPe",role:"Software Backend Intern — Java",type:"Internship",location:"Remote · India",mode:"Remote",pay:"₹30,000–₹40,000/month",postedOn:"2026-09-03",posted:"Posted 03 Sep 2026",deadline:"Applications open",urgent:true,eligibility:"2026 and 2027 graduates",confidence:"Medium-High · live Apply Now button",about:"Build production backend services in Java and Spring Boot, design REST APIs and work with SQL-backed systems in a remote fintech team. The role expects strong Java fundamentals and previous hands-on engineering work.",apply:"https://hiredoor.in/jobs/software-backend-intern-java--42735f",source:"https://hiredoor.in/jobs/software-backend-intern-java--42735f"},
    {id:"h2loop-ai-engineer-intern",company:"H2Loop",role:"AI Engineer Intern",type:"Internship",location:"Bengaluru",mode:"Onsite",pay:"₹40,000–₹50,000/month",postedOn:"2026-08-31",posted:"Shared 31 Aug 2026",deadline:"Applications open",urgent:false,eligibility:"Students and freshers",confidence:"Medium-High · live Apply Now button",about:"Build agentic developer tools across large TypeScript and JavaScript codebases. The work includes coding agents, React or SolidJS interfaces, command-line tooling and MCP-connected workflows.",apply:"https://hiredoor.in/jobs/ai-engineer-intern-971e49",source:"https://hiredoor.in/jobs/ai-engineer-intern-971e49"},
    {id:"medibuddy-ai-ml-intern-ppo",company:"MediBuddy",role:"AI/ML Engineering Intern + PPO",type:"Internship + PPO",location:"Bengaluru",mode:"Onsite",pay:"₹35,000–₹40,000/month",postedOn:"2026-08-30",posted:"Shared 30 Aug 2026",deadline:"Applications open",urgent:false,eligibility:"2026 and 2027 graduates",confidence:"High · live application form",about:"Build a production AI assistant using agents, RAG, LangGraph or LangChain, MCP servers, evaluation pipelines, FastAPI and AWS. The internship includes a possible pre-placement offer.",apply:"https://docs.google.com/forms/d/e/1FAIpQLSee5VQHD1Ht_goUqnJD6z2cbFhiafdOD7xfm2-iHcGWfDf5Gw/viewform",source:"https://hiredoor.in/jobs/ai-ml-engineering-intern-ppo--cb6e93"},
    {id:"medibuddy-web-platform-intern",company:"MediBuddy",role:"Web Platform Engineering Intern",type:"Internship",location:"Bengaluru / Indore",mode:"Onsite",pay:"₹35,000–₹40,000/month",postedOn:"2026-08-30",posted:"Shared 30 Aug 2026",deadline:"Applications open",urgent:false,eligibility:"2026 and 2027 graduates",confidence:"High · live application form",about:"Own web-platform features end to end with React, Next.js, TypeScript, Tailwind, TanStack and NX, including API integrations, testing and production delivery.",apply:"https://docs.google.com/forms/d/e/1FAIpQLSee5VQHD1Ht_goUqnJD6z2cbFhiafdOD7xfm2-iHcGWfDf5Gw/viewform",source:"https://hiredoor.in/jobs/software-engineering-intern-web-platform-920ddc"},
    {id:"mynaksh-data-analyst-intern",company:"MyNaksh",role:"Data Analyst Intern + PPO",type:"Internship + PPO",location:"Bengaluru",mode:"Onsite",pay:"₹30,000–₹35,000/month",postedOn:"2026-08-30",posted:"Shared 30 Aug 2026",deadline:"Applications open",urgent:false,eligibility:"2025, 2026 and 2027 graduates",confidence:"High · live application form",about:"Analyse business and product data using SQL, Excel or Google Sheets and statistics; build dashboards in Power BI or Tableau and automate analysis with Python, Pandas and NumPy. The role includes a possible PPO.",apply:"https://docs.google.com/forms/d/e/1FAIpQLSfZa2zDIiHfgMQo7KQSEUG2lsIx4unxX5lwg8ncvCG_SZYODw/viewform",source:"https://hiredoor.in/jobs/data-analyst-intern-ppo--71c67b"},
    {id:"flexday-ai-engineering-intern",company:"flexday.ai",role:"AI Engineering Intern + PPO",type:"Internship + PPO",location:"Remote · India",mode:"Remote",pay:"₹30,000/month",postedOn:"2026-08-30",posted:"Shared 30 Aug 2026",deadline:"Applications open",urgent:false,eligibility:"2025, 2026 and 2027 graduates",confidence:"High · live Apply Now button",about:"Test and evaluate AI outputs, improve prompts, detect hallucinations and build regression, functional and evaluation datasets for AI products. The internship includes a possible PPO.",apply:"https://www.flexday.ai/careers/ai-evaluation-engineer-intern",source:"https://hiredoor.in/jobs/ai-engineering-intern-ppo--b44467"}
  ],
  watchlist: [
    {status:"Eligibility conflict",company:"Actionpackd",role:"Software Engineering Intern + PPO",pay:"₹30,000/month",reason:"Shared within the last week, but the recruiter post limits eligibility to 2025/2026 while another listing says current students. Excluded until 2027 eligibility is confirmed.",source:"https://hiredoor.in/jobs/software-engineering-intern-ppo--9b95ac"},
    {status:"Closed",company:"Jumbo Consulting",role:"Software Development Engineer Intern",pay:"₹50,000/month",reason:"Shared within the last week, but the application listing is no longer accepting applications.",source:"https://www.linkedin.com/jobs/"},
    {status:"Pay conflict",company:"Microsoft",role:"AI/ML Research Intern",pay:"₹25,000–₹1,00,000/month · conflicting reports",reason:"The recent reports disagree on compensation and one reported minimum is below ₹30,000. Excluded until pay is verified.",source:"https://apply.careers.microsoft.com/careers"},
    {status:"Below threshold",company:"SentLogic",role:"Software Engineer Intern",pay:"₹25,000–₹30,000/month",reason:"Recently shared, but the pay range can fall below the strict ₹30,000 monthly minimum.",source:"https://hiredoor.in/"},
    {status:"Below threshold",company:"HuntingCube",role:"Software Engineer Intern",pay:"₹7.2–₹7.92 LPA",reason:"Recently shared, but the reported full-time-equivalent pay is below the strict ₹8 LPA floor.",source:"https://hiredoor.in/"}
  ]
};
