// Automated job-radar runs update this file. Keep each id stable so saved user progress survives data refreshes.
window.ROLEBOARD_DATA = {
  updated: "07 Sep 2026",
  jobs: [
    {id:"weekday-swe-intern",company:"Weekday Works",role:"Software Engineer Intern",type:"Internship",location:"Bengaluru / Remote",mode:"Remote",pay:"₹30,000–₹50,000/month",postedOn:"2026-09-03",posted:"Posted 03 Sep 2026",deadline:"Applications open",urgent:true,eligibility:"2026 and 2027 graduates",confidence:"Medium-High · live Apply Now button",about:"Work alongside experienced engineers on real software projects, assisting with feature design, development, testing, debugging and performance improvements. The broad requirements accept Python, JavaScript, Java or C++ plus DSA, GitHub, cloud and AI/ML exposure.",apply:"https://hiredoor.in/jobs/software-engineer-intern-e43f12",source:"https://hiredoor.in/jobs/software-engineer-intern-e43f12"},
    {id:"pearson-payroll-frontend-intern",company:"Pearson",role:"Software Engineering Intern — Global Payroll Technology",type:"Internship",location:"Bengaluru",mode:"Hybrid",pay:"₹30,000/month",postedOn:"2026-09-03",posted:"Posted 03 Sep 2026",deadline:"Applications open",urgent:true,eligibility:"2026 and 2027 graduates",confidence:"High · live employer application",about:"Build React and TypeScript interfaces for Pearson's Global Command Center, an enterprise payroll operations and analytics platform. Responsibilities include reusable responsive components, dashboards, REST API integration, debugging, testing and performance optimisation.",apply:"https://pearson.jobs/bangalore-ind/associate-software-engineer-intern/60B518B3E9E74BF6BA34DD5D28B23DEE/job/",source:"https://hiredoor.in/jobs/software-engineering-intern-global-payroll-technology-team-2d610d"},
    {id:"h2loop-ai-engineer-intern",company:"H2Loop",role:"AI Engineer Intern",type:"Internship",location:"Bengaluru",mode:"Onsite",pay:"₹40,000–₹50,000/month",postedOn:"2026-08-31",posted:"Shared 31 Aug 2026",deadline:"Applications open",urgent:false,eligibility:"Students and freshers",confidence:"Medium-High · live Apply Now button",about:"Build agentic developer tools across large TypeScript and JavaScript codebases. The work includes coding agents, React or SolidJS interfaces, command-line tooling and MCP-connected workflows.",apply:"https://hiredoor.in/jobs/ai-engineer-intern-971e49",source:"https://hiredoor.in/jobs/ai-engineer-intern-971e49"},
  ],
  watchlist: [
    {status:"Stale source",company:"NxtPe",role:"Backend, React Frontend and Product Management Internships",pay:"₹30,000–₹40,000/month",reason:"The application forms remain live, but the original recruiter post was published on 20 Aug 2026, not 02 Sep. Removed from qualified roles because the opening is more than seven days old.",source:"https://www.linkedin.com/posts/deeksha-jain-4ba449191_hiring-internship-softwareengineering-activity-7496196106939215872-6G8p"},
    {status:"Eligibility conflict",company:"Actionpackd",role:"Software Engineering Intern + PPO",pay:"₹30,000/month",reason:"Shared within the last week, but the recruiter post limits eligibility to 2025/2026 while another listing says current students. Excluded until 2027 eligibility is confirmed.",source:"https://hiredoor.in/jobs/software-engineering-intern-ppo--9b95ac"},
    {status:"Closed / wrong link",company:"HARMAN",role:"Purported Software Engineering Intern",pay:"₹50,000–₹65,000/month · unverified",reason:"A fresh repost pointed to this application, but the link resolves to a Certification Intern listing posted three weeks ago and marked no longer accepting applications. Excluded as a misleading repost.",source:"https://www.linkedin.com/jobs/view/4448767325/"},
    {status:"Stale / disabled",company:"Futures First",role:"Python Developer Intern + PPO",pay:"₹50,000–₹60,000/month",reason:"The live listing is eight days old and its Apply Now button is disabled. It fails both the seven-day freshness rule and the open-application rule.",source:"https://hiredoor.in/jobs/python-developer-intern-ppo--68e33d"},
    {status:"Stale",company:"Thinkly AI",role:"Forward Deployed Engineer Intern + PPO",pay:"₹30,000–₹45,000/month",reason:"The application is still enabled, but the live listing is eight days old. Excluded because the board's maximum age is seven days.",source:"https://hiredoor.in/jobs/forward-deployed-engineer-intern-ppo--367bea"},
    {status:"Pay not verified",company:"Spyne",role:"Software Development Engineer Intern",pay:"Reported ₹30,000/month · not stated by employer",reason:"The employer application is live and the role was recently shared, but the official JD does not state a stipend. Excluded until compensation at or above ₹30,000 is confirmed.",source:"https://spyneai.keka.com/careers/jobdetails/156605"},
    {status:"Pay / date conflict",company:"Enterpret",role:"Software Engineering Intern",pay:"Conflicting third-party ranges",reason:"The official Greenhouse application is open, but it gives neither a posting date nor exact stipend; recent sources disagree on pay. The JD also requires a Tier-1 college. Excluded pending direct verification.",source:"https://job-boards.greenhouse.io/enterpret/jobs/7847134003"},
    {status:"Wrong batch",company:"Planbow",role:"Software Engineer Intern",pay:"Meets reported stipend floor",reason:"A recent company post limits the opening to 2025 and 2026 graduates, so a May 2027 graduate is not eligible.",source:"https://www.linkedin.com/company/planbow/"}
  ]
};
