// Automated job-radar runs update this file. Keep each id stable so saved user progress survives data refreshes.
window.ROLEBOARD_DATA = {
  updated: "15 Sep 2026",
  jobs: [
    {id:"ixigo-fullstack-intern-b2b-2026",company:"ixigo",role:"Full-Stack Intern - B2B",type:"Internship",location:"Gurugram",mode:"On-site",pay:"₹40,000/month · marketplace-reported",postedOn:"2026-09-15",posted:"Listed 15 Sep 2026",deadline:"Official application live",applicationOpen:true,urgent:true,eligibility:"Pursuing or recently completed CS/engineering degree; 2027 listed by reviewed marketplace",confidence:"High for role and live application · medium for pay and batch detail",about:"Build and scale ixigo's Voice AI stack across voice bots, queue/retry frameworks, backend infrastructure, data pipelines and internal dashboards. The stack includes Python, TypeScript/Node.js, FastAPI/Flask, PostgreSQL, Redis, AWS, Docker, CI/CD and Kubernetes/EKS.",apply:"https://jobs.smartrecruiters.com/oneclick-ui/company/ixigo/publication/6f37e9a6-38b0-460c-b734-0f6ef04e47db?dcr_ci=ixigo",source:"https://hiredoor.in/jobs/software-full-stack-intern-7c9d04"},
    {id:"zyaro-ai-swe-intern-2026",company:"Zyaro",role:"AI Software Engineering Intern + PPO",type:"Internship + PPO",location:"Gurugram",mode:"On-site",pay:"₹30,000–₹35,000/month",postedOn:"2026-09-15",posted:"Listed 15 Sep 2026",deadline:"Apply button live",applicationOpen:true,urgent:true,eligibility:"2026, 2027 and 2028 batches listed",confidence:"Medium · reviewed marketplace listing; employer profile verification is pending",about:"Translate customer needs into AI software solutions, build and operate those solutions, and own customer outcomes after deployment. The public JD is unusually broad and does not disclose a concrete engineering stack.",apply:"https://hiredoor.in/jobs/ai-software-engineering-intern-ppo--b7ac1a",source:"https://hiredoor.in/jobs/ai-software-engineering-intern-ppo--b7ac1a"},
    {id:"qualifycode-swe-intern-2026",company:"QualifyCode",role:"Software Engineer Intern",type:"Internship + PPO",location:"Mumbai",mode:"Hybrid / on-site",pay:"₹35,000/month · recruiter-reported",postedOn:"2026-09-12",posted:"Employer listing live 15 Sep",deadline:"LinkedIn Apply live",applicationOpen:true,urgent:true,eligibility:"Pursuing or recently completed CS/IT degree; recruiter states 2026/2027",confidence:"High for role and application · medium for exact pay",about:"Ship features across a web IDE, candidate flows and recruiter dashboards; build low-latency services, secure code-execution pipelines and LLM workflows. The stack includes React, Next.js, TypeScript, Python/Node/Go, REST, WebSockets, PostgreSQL, Redis, Docker and Git.",apply:"https://in.linkedin.com/jobs/view/software-engineer-intern-at-qualifycode-4461137885",source:"https://qualifycode.com/careers/"},
    {id:"mobond-software-developer-intern-2026",company:"Mobond Software",role:"Software Developer Intern",type:"Internship",location:"Navi Mumbai",mode:"Remote",pay:"₹30,000/month",postedOn:"2026-09-12",posted:"Listed 12 Sep 2026",deadline:"Apply button live",applicationOpen:true,urgent:true,eligibility:"2025, 2026 and 2027 batches listed",confidence:"Medium · reviewed marketplace listing; employer profile verification is pending",about:"Develop backend software using Java or a similar language, REST APIs, JSON, SQL/NoSQL databases and Git, with possible exposure to cloud, AI/ML, data processing, search and large-scale applications.",apply:"https://hiredoor.in/jobs/software-developer-intern-4988aa",source:"https://hiredoor.in/jobs/software-developer-intern-4988aa"},
    {id:"weekday-swe-intern-2026",company:"Weekday Works",role:"Software Engineer Intern",type:"Internship",location:"Bengaluru",mode:"Remote",pay:"₹30,000–₹50,000/month",postedOn:"2026-09-03",posted:"Posted 03 Sep 2026",deadline:"Apply button still live",applicationOpen:true,urgent:false,eligibility:"2026 and 2027 batches listed; current or recent CS/engineering student",confidence:"Medium · listing is reviewed but employer profile verification is pending",about:"Help design, develop and test software features, debug issues, improve performance and contribute to engineering workflows. The JD asks for basic DSA, software-development principles and one language such as Python, JavaScript, Java or C++.",apply:"https://hiredoor.in/jobs/software-engineer-intern-e43f12",source:"https://hiredoor.in/jobs/software-engineer-intern-e43f12"},
    {id:"bright-money-sde-intern-2026",company:"Bright Money",role:"SDE Intern",type:"Internship",location:"Bengaluru",mode:"On-site",pay:"₹50,000/month",postedOn:"2026-08-05",posted:"Posted about 41 days ago",deadline:"Apply button still live",applicationOpen:true,urgent:false,eligibility:"Freshers",confidence:"Medium · reviewed marketplace listing; employer profile verification is pending",about:"Build backend systems and scalable services, optimize APIs and write production-quality code. The JD emphasizes DSA, Python or backend development, REST APIs and SQL, with Django or Node.js in the listed skills.",apply:"https://hiredoor.in/jobs/sde-intern-5cb3c7",source:"https://hiredoor.in/jobs/sde-intern-5cb3c7"},
    {id:"truefoundry-backend-intern",company:"TrueFoundry",role:"Software Engineer Backend Intern",type:"Internship",location:"India",mode:"Remote",pay:"₹45,000–₹55,000/month",postedOn:"2026-03-15",posted:"Older listing · employer active",deadline:"Wellfound Apply live",applicationOpen:true,urgent:false,eligibility:"No experience required; India remote",confidence:"Medium-high · live company profile and transparent pay; listing itself is old",about:"Work with the founders to build TrueFoundry's developer and data-science platform. The public listing emphasizes Python or Java, direct ownership, product and business discussions, and full-time remote work.",apply:"https://wellfound.com/jobs/2153913-software-engineer-backend-intern-remote",source:"https://wellfound.com/jobs/2153913-software-engineer-backend-intern-remote"}
  ],
  watchlist: [
    {status:"Pay not verified",company:"DataCore Software",role:"Software Intern (AI)",pay:"Estimated ₹30,000–₹40,000/month · not stated by DataCore",reason:"The employer application is live and explicitly targets 2027 graduates, but DataCore does not publish a stipend. The only current pay figure is labelled an estimate, so the role cannot pass the ₹30,000 hard floor yet.",source:"https://www.datacore.com/careers/job/706876/"},
    {status:"Source date / pay not verified",company:"Stripe",role:"Software Engineer, Intern",pay:"Reported ₹1,00,000/month · not stated by Stripe",reason:"Stripe's Bengaluru application is live, but the employer page gives neither a posting date nor an India pay range. A recent aggregator timestamp is not proof of a newly opened role, so it fails both hard-source checks.",source:"https://stripe.com/careers/listing/software-engineer-intern/8031833"},
    {status:"Stale / pay not verified",company:"Microsoft",role:"Software Engineering Intern",pay:"Reported ₹1.25 lakh/month · not stated by Microsoft",reason:"Microsoft's application remains live, but independent indexing traces the original opening to 01 Jul 2026 and Microsoft does not disclose India pay. It fails the seven-day freshness and confirmed-pay rules.",source:"https://apply.careers.microsoft.com/careers/job/1970393556911730"},
    {status:"Source date / pay not verified",company:"SymphonyAI",role:"Apprentice — Software Engineer",pay:"Reported ₹40,000/month · not employer-confirmed",reason:"The reviewed aggregator listing is recent and lists 2027 eligibility, but no dated employer posting or employer-confirmed compensation was located. It cannot remain qualified under the strict source rules.",source:"https://hiredoor.in/jobs/apprentice-software-engineer-c1c03c"},
    {status:"Stale",company:"Interview Kickstart",role:"Intern - Software Development Engineer (Backend)",pay:"₹60,000/month",reason:"The employer-linked application was previously verified open, but its original posting date was 03 Sep 2026. It is now more than seven calendar days old and fails the strict freshness rule.",source:"https://jobs.blume.vc/companies/interview-kickstart-2/jobs/92064480-intern-software-development-engineer-backend"},
    {status:"Stale",company:"Pearson",role:"Software Engineering Intern — Global Payroll Technology",pay:"₹30,000/month",reason:"The employer application was previously verified open, but the original posting date was 03 Sep 2026. It is now more than seven calendar days old and fails the strict freshness rule.",source:"https://pearson.jobs/bangalore-ind/associate-software-engineer-intern/60B518B3E9E74BF6BA34DD5D28B23DEE/job/"},
    {status:"Source date / pay unavailable",company:"Amazon",role:"SDE I Intern — University Talent Acquisition",pay:"Not disclosed by Amazon",reason:"The employer application is live, explicitly accepts 2027 graduates, and is a six-month in-person internship from Jan–Jun 2027 across several Indian cities. Resume fit: 84%. Evidence: Python/C++, databases, testing, projects and a prior software internship. Gaps: no proven large-scale distributed-system work, and you must confirm that college permits six months full-time. It stays outside qualified roles because Amazon publishes neither the opening date nor stipend.",source:"https://www.amazon.jobs/en/jobs/10508052/sde-i-intern-amazon-university-talent-acquisition"},
    {status:"Source date unavailable",company:"Uniprep",role:"Software Developer",pay:"₹12–₹25 LPA",reason:"The Apply button is live and the listing accepts zero years of experience. Resume fit: 90%. Evidence: its Python/JavaScript/C++/SQL/REST/Git requirements closely match your resume. Gaps: the listing gives no original posting date or assurance that a May 2027 graduate can defer joining, so it cannot pass the freshness and availability checks.",source:"https://cutshort.io/job/Software-Developer-Uniprep-QtpW40Gy"},
    {status:"Closed after recent indexing",company:"FrontPage",role:"Software Engineering Intern — AI-Native Product Engineering",pay:"₹30,000–₹50,000/month",reason:"Resume fit: 88%. Evidence: your Django/FastAPI APIs, React/TypeScript UI, SQL, AI product projects and debugging experience align strongly. Gaps: no Redis or production-scale realtime system evidence. A search result indexed this role recently, but the employer application now returns 404, so it is not open and is excluded.",source:"https://www.ycombinator.com/companies/frontpage/jobs/i7yAbdy-software-engineering-intern-ai-native-product-engineering"},
    {status:"Pay floor not guaranteed",company:"SuperKalam",role:"AI Applied Engineer — Voice-First Internship",pay:"₹25,000–₹40,000/month",reason:"The employer application is live, but the published minimum is below your ₹30,000 threshold. Resume fit: 66%. Evidence: Python, RAG, API and full-stack experience. Gaps: no demonstrated STT/TTS, voice-agent, latency-budget or production evaluation work; calling this a high match would be dishonest.",source:"https://www.ycombinator.com/companies/superkalam/jobs/DKwCjWa-ai-applied-engineer-voice-first-internship"},
    {status:"Pay / source provenance unverified",company:"Visa",role:"Software Engineer Intern — 2027",pay:"₹70,000/month claimed by aggregator · not confirmed by Visa",reason:"A fresh listing claims 2027 eligibility, a Jun 2027 start and a ₹70,000 stipend, but its Apply flow does not expose a transparent employer destination and Visa's official evergreen intern page does not confirm those details. Resume fit: 58%. Gaps: no Java/Spring, Kubernetes or Kafka evidence. Held back until an employer-hosted requisition verifies the role and pay.",source:"https://myinternships.in/internships/37"},
    {status:"No direct employer application",company:"MediBuddy",role:"Software Engineering Intern + PPO",pay:"₹35,000–₹40,000/month claimed in third-party post",reason:"A fresh post names 2026/2027 eligibility, but it asks candidates to comment for a link and provides no employer-hosted JD or application. Resume fit: approximately 74% from the generic description, not a reliable ATS match. Excluded because the role, pay and application route cannot be independently verified.",source:"https://www.linkedin.com/posts/asharsi_medibuddy-is-%F0%9D%97%B5%F0%9D%97%B6%F0%9D%97%BF%F0%9D%97%B6%F0%9D%97%BB%F0%9D%97%B4-software-engineering-activity-7498952253802803200-7m4u"},
    {status:"Closed referral window",company:"Atlan",role:"AI-Native Builder Internship",pay:"₹50,000/month reported · not stated on current employer page",reason:"Recent reposts imply this is newly open, but Atlan's official page says referral-only and lists a 06–18 Aug 2026 referral window. Resume fit: 79%. Evidence: full-stack development, AI-assisted systems and end-to-end ownership. Gap: no direct referral and the employer window has ended, so the repost is not an actionable opening.",source:"https://intern.at.atlan.com/"},
    {status:"Pay not confirmed",company:"Certa",role:"Frontend Engineer Intern",pay:"₹1,00,000/month claimed by marketplace · employer says only 'competitive'",reason:"The remote six-month internship and application appear live. Resume fit: 82%. Evidence: React, TypeScript, APIs and deployed projects. Gaps: no Next.js, Figma workflow, accessibility or measured frontend-performance evidence. Held back because the exact pay is not confirmed by Certa.",source:"https://simplify.jobs/p/f7843e36-e0e4-4531-866f-60aa4149321f/Frontend-Engineer-Intern"},
    {status:"Deadline passed",company:"Tower Research Capital",role:"AI/ML Intern",pay:"Not disclosed by employer · conflicting third-party estimates",reason:"The role fits 2027 and starts Jan 2027, but a source-specific application deadline was 07 Sep 2026. Resume fit: 49%. Evidence: Python, SQL, Git, PyTorch and one ML workflow. Gaps: no multi-agent system, MLOps, model productionization, Linux/Bash depth or advanced ML research. Excluded as expired despite fresh reposts.",source:"https://api.unstop.com/internships/aiml-internship-tower-research-capital-india-private-limited-1743622"},
    {status:"Stale",company:"H2Loop",role:"AI Engineer Intern",pay:"₹40,000–₹50,000/month",reason:"The application is still enabled, but the opening is now more than seven calendar days old. Removed from qualified roles under the strict freshness rule.",source:"https://hiredoor.in/jobs/ai-engineer-intern-971e49"},
    {status:"Stale source",company:"NxtPe",role:"Backend, React Frontend and Product Management Internships",pay:"₹30,000–₹40,000/month",reason:"The application forms remain live, but the original recruiter post was published on 20 Aug 2026, not 02 Sep. Removed from qualified roles because the opening is more than seven days old.",source:"https://www.linkedin.com/posts/deeksha-jain-4ba449191_hiring-internship-softwareengineering-activity-7496196106939215872-6G8p"},
    {status:"Eligibility conflict",company:"Actionpackd",role:"Software Engineering Intern + PPO",pay:"₹30,000/month",reason:"Shared within the last week, but the recruiter post limits eligibility to 2025/2026 while another listing says current students. Excluded until 2027 eligibility is confirmed.",source:"https://hiredoor.in/jobs/software-engineering-intern-ppo--9b95ac"},
    {status:"Closed / wrong link",company:"HARMAN",role:"Purported Software Engineering Intern",pay:"₹50,000–₹65,000/month · unverified",reason:"A fresh repost pointed to this application, but the link resolves to a Certification Intern listing posted three weeks ago and marked no longer accepting applications. Excluded as a misleading repost.",source:"https://www.linkedin.com/jobs/view/4448767325/"},
    {status:"Stale / disabled",company:"Futures First",role:"Python Developer Intern + PPO",pay:"₹50,000–₹60,000/month",reason:"The listing is now more than seven days old and its Apply Now button is disabled. It fails both the freshness and open-application rules.",source:"https://hiredoor.in/jobs/python-developer-intern-ppo--68e33d"},
    {status:"Stale",company:"Thinkly AI",role:"Forward Deployed Engineer Intern + PPO",pay:"₹30,000–₹45,000/month",reason:"The application is still enabled, but the listing is now more than seven days old. Excluded because the board's maximum age is seven days.",source:"https://hiredoor.in/jobs/forward-deployed-engineer-intern-ppo--367bea"},
    {status:"Pay not verified",company:"Spyne",role:"Software Development Engineer Intern",pay:"Expected ₹40,000/month in recruiter post · not stated by Spyne",reason:"The employer application is live and a fresh 15 Sep post names 2027–2029 students. Resume fit: 81%. Evidence: React, APIs, databases, Git and software-intern experience. Gap: Node.js is not on your resume. The official JD still gives no stipend, so the claimed ₹40,000 cannot satisfy the hard pay check.",source:"https://spyneai.keka.com/careers/jobdetails/156605"},
    {status:"Pay / date conflict",company:"Enterpret",role:"Software Engineering Intern",pay:"Conflicting third-party ranges",reason:"The official Greenhouse application is open, but it gives neither a posting date nor exact stipend; recent sources disagree on pay. The JD also requires a Tier-1 college. Excluded pending direct verification.",source:"https://job-boards.greenhouse.io/enterpret/jobs/7847134003"},
    {status:"Wrong batch",company:"Planbow",role:"Software Engineer Intern",pay:"Meets reported stipend floor",reason:"A recent company post limits the opening to 2025 and 2026 graduates, so a May 2027 graduate is not eligible.",source:"https://www.linkedin.com/company/planbow/"}
  ]
};
