// Conservative, resume-evidence-only assessments. Scores are not hiring probabilities.
window.ROLEBOARD_MATCHES = {
  "razorpay-ai-builder-2026": [82, "Evidence: shipped RAG, prompt-engineering and full-stack systems. Gap: no demonstrated production agent framework or large-scale AI ownership."],
  "truefoundry-backend-intern": [72, "Evidence: Python backends, APIs, Docker, AWS and CI/CD. Gap: no Kubernetes, ML-platform or internal developer-platform delivery shown."],
  "ecl-fullstack-intern-2027": [86, "Evidence: Django/DRF, React, SQL databases, AWS and shipped business software closely match. Gap: TypeScript and fintech/lending experience are not demonstrated."],
  "teal-ai-ml-intern": [83, "Evidence: RAG, NLP, PyTorch and ML API work are directly relevant. Gap: no shipped OCR, entity resolution, BERT fine-tuning, embedding search or reranking system."],
  "lexsi-ai-research-intern": [52, "Evidence: PyTorch, RAG and LLM experimentation provide a base. Gap: no research publication, transformer fine-tuning, reinforcement learning, alignment or interpretability work."],
  "superkalam-fullstack-intern": [78, "Evidence: React, backend APIs, PostgreSQL/Redis and RAG align. Gap: Next.js, NestJS and high-scale production ownership are not shown."],
  "discover-dollar-sde-intern": [77, "Evidence: JavaScript, Python, React and SQL/NoSQL work match the general stack. Gap: Node/NestJS and Angular experience are absent."],
  "medibuddy-ai-ml-intern-ppo": [86, "Evidence: RAG, FastAPI, AWS, prompt engineering and production-style backends align strongly. Gap: no LangGraph/LangChain, MCP server or formal LLM-evaluation pipeline is demonstrated."],
  "medibuddy-web-platform-intern": [72, "Evidence: React, REST APIs and end-to-end product delivery match. Gap: Next.js, TypeScript and web-platform scale are not demonstrated."],
  "nxtpe-java-backend-intern": [45, "Evidence: REST, SQL and backend fundamentals transfer. Gap: Java and Spring Boot—the core stack—do not appear on the resume."],
  "kreeda-ai-ml-intern": [82, "Evidence: Python, PyTorch, scikit-learn, RAG and ML API work match well. Gap: no TensorFlow or production vector-database implementation is shown."],
  "thinkly-forward-deployed-intern": [61, "Evidence: prompt iteration, backend debugging and requirements ownership help. Gap: no voice AI, telephony, live-call debugging or client-deployment track record."],
  "craftech360-fullstack-intern": [76, "Evidence: React, JavaScript, APIs and multiple shipped database-backed apps align. Gap: Node.js experience is not listed."],
  "flexday-ai-engineering-intern": [60, "Evidence: prompt engineering and API automation testing are relevant. Gap: no formal hallucination testing, LLM regression suite or evaluation-dataset ownership."],
  "growth99-ai-java-intern": [48, "Evidence: AI workflow and backend experience are useful. Gap: Java—the role's primary language—is not on the resume."],
  "raptee-go-intern": [38, "Evidence: backend and systems fundamentals transfer. Gap: no Go, production concurrency, networking or distributed-systems delivery."],
  "fancode-backend-intern": [65, "Evidence: DSA, REST, databases and backend project work are relevant. Gap: large-scale production systems are not shown and semester eligibility needs confirmation."],
  "fancode-devops-intern": [52, "Evidence: Docker, AWS, CI/CD and cloud certifications create a base. Gap: no production Kubernetes, Terraform, observability or infrastructure operations."],
  "weekday-swe-intern": [74, "Evidence: Python, JavaScript, C++, DSA and several shipped applications meet the broad requirements. Gap: the client, exact stack and engineering scope are undisclosed."],
  "pearson-payroll-frontend-intern": [79, "Evidence: React, JavaScript, HTML/CSS and REST integrations are demonstrated. Gap: TypeScript, SPFx, Microsoft Graph and Azure frontend delivery are not shown."],
  "actionpackd-swe-intern": [76, "Evidence: Python/C++, APIs, databases, Git and shipped projects match the generalist role. Gap: TypeScript and formal code-review/open-source evidence are limited."],
  "gnani-fullstack-ai-intern": [78, "Evidence: React, Python/FastAPI, RAG and end-to-end product delivery are relevant. Gap: no Node.js, TypeScript, voice-agent or million-user scale evidence."],
};
