// Conservative, resume-evidence-only assessments. Scores are not hiring probabilities.
window.ROLEBOARD_MATCHES = {
  "ixigo-fullstack-intern-b2b-2026": [67, "Evidence: Python, TypeScript, FastAPI/Flask, PostgreSQL, AWS, Docker, CI/CD and dashboard delivery match the general stack. Gap: no demonstrated Voice AI, STT/TTS, Node.js, Redis, queue scheduling or Kubernetes/EKS work; those are central, not minor extras."],
  "zyaro-ai-swe-intern-2026": [76, "Evidence: stakeholder requirements, end-to-end delivery and operating business software map directly to the stated work. Gap: the JD is too vague to prove a stronger technical match, and your resume does not show customer-facing deployment support."],
  "qualifycode-swe-intern-2026": [84, "Evidence: React, TypeScript, Python, REST, WebSockets, SQL, Docker, Git and RAG projects align across most of the stack. Gap: no Next.js, Node.js, Redis, Monaco/editor tooling, Linux depth or secure code-execution pipeline is demonstrated."],
  "mobond-software-developer-intern-2026": [85, "Evidence: Python backend work, REST/JSON, SQL and NoSQL databases, Git, cloud exposure and a prior software internship cover nearly all published requirements. Gap: Java is not on the resume and the claimed large-scale/search exposure is only prospective."],
  "weekday-swe-intern-2026": [86, "Evidence: Python/JavaScript/C++, shipped software, testing, debugging and a prior internship exceed the role's basic programming requirements. Gap: the resume does not explicitly prove DSA practice or formal multi-engineer code-review experience."],
  "bright-money-sde-intern-2026": [82, "Evidence: Python, Django, REST APIs, SQL, performance work and backend delivery are directly relevant. Gap: DSA strength is not evidenced on the resume, Node.js is absent, and production-scale financial backend ownership is not shown."],
  "razorpay-ai-builder-2026": [82, "Evidence: shipped RAG, prompt-engineering and full-stack systems. Gap: no demonstrated production agent framework or large-scale AI ownership."],
  "truefoundry-backend-intern": [72, "Evidence: Python backends, APIs, Docker, AWS and CI/CD. Gap: no Kubernetes, ML-platform or internal developer-platform delivery shown."],
  "ecl-fullstack-intern-2027": [86, "Evidence: Django/DRF, React, SQL databases, AWS and shipped business software closely match. Gap: TypeScript and fintech/lending experience are not demonstrated."],
  "teal-ai-ml-intern": [83, "Evidence: RAG, NLP, PyTorch and ML API work are directly relevant. Gap: no shipped OCR, entity resolution, BERT fine-tuning, embedding search or reranking system."],
  "lexsi-ai-research-intern": [52, "Evidence: PyTorch, RAG and LLM experimentation provide a base. Gap: no research publication, transformer fine-tuning, reinforcement learning, alignment or interpretability work."],
  "superkalam-fullstack-intern": [78, "Evidence: React, backend APIs, PostgreSQL/Redis and RAG align. Gap: Next.js, NestJS and high-scale production ownership are not shown."],
  "discover-dollar-sde-intern": [77, "Evidence: JavaScript, Python, React and SQL/NoSQL work match the general stack. Gap: Node/NestJS and Angular experience are absent."],
  "kreeda-ai-ml-intern": [82, "Evidence: Python, PyTorch, scikit-learn, RAG and ML API work match well. Gap: no TensorFlow or production vector-database implementation is shown."],
  "thinkly-forward-deployed-intern": [61, "Evidence: prompt iteration, backend debugging and requirements ownership help. Gap: no voice AI, telephony, live-call debugging or client-deployment track record."],
  "craftech360-fullstack-intern": [76, "Evidence: React, JavaScript, APIs and multiple shipped database-backed apps align. Gap: Node.js experience is not listed."],
  "growth99-ai-java-intern": [48, "Evidence: AI workflow and backend experience are useful. Gap: Java—the role's primary language—is not on the resume."],
  "raptee-go-intern": [38, "Evidence: backend and systems fundamentals transfer. Gap: no Go, production concurrency, networking or distributed-systems delivery."],
  "fancode-backend-intern": [65, "Evidence: DSA, REST, databases and backend project work are relevant. Gap: large-scale production systems are not shown and semester eligibility needs confirmation."],
  "fancode-devops-intern": [52, "Evidence: Docker, AWS, CI/CD and cloud certifications create a base. Gap: no production Kubernetes, Terraform, observability or infrastructure operations."],
  "actionpackd-swe-intern": [76, "Evidence: Python/C++, APIs, databases, Git and shipped projects match the generalist role. Gap: TypeScript and formal code-review/open-source evidence are limited."],
  "gnani-fullstack-ai-intern": [78, "Evidence: React, Python/FastAPI, RAG and end-to-end product delivery are relevant. Gap: no Node.js, TypeScript, voice-agent or million-user scale evidence."],
};
